### ISSUE TITLE
首页消息查看，到底后显示白屏

### ISSUE THREAD

**Issue by alhoward2021** [guozhigq/pilipala#295]
### 问题描述
请提供一个清晰而简明的问题描述。
首页消息查看，到底后显示白屏
### 复现步骤
请提供复现该问题所需的具体步骤。
点开首页右上角小铃铛后滑倒最后，立刻看到
### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
能定位到哪条消息附近吗

**Comment by PRO-2684** [comment]
1.0.21 版本仍然存在此问题@guozhigq 

![Screenshot_2024-03-14-14-33-31-810_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/54608551/a122cf8d-4c0c-49af-a1a2-420bdd739afd)

**Comment by guozhigq** [comment]
> 1.0.21 版本仍然存在此问题@guozhigq 
> 
> ![Screenshot_2024-03-14-14-33-31-810_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/54608551/a122cf8d-4c0c-49af-a1a2-420bdd739afd)
> 

可以看下是什么私信内容吗

**Comment by PRO-2684** [comment]
> > 1.0.21 版本仍然存在此问题@guozhigq
> > ![Screenshot_2024-03-14-14-33-31-810_com guozhigq pilipala](https://private-user-images.githubusercontent.com/54608551/312726975-a122cf8d-4c0c-49af-a1a2-420bdd739afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjI2ODQsIm5iZiI6MTcxMDQ2MjM4NCwicGF0aCI6Ii81NDYwODU1MS8zMTI3MjY5NzUtYTEyMmNmOGQtNGMwYy00OWFmLWExYTItNDIwYmRkNzM5YWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAwMjYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZGQ3OGE2ZGE3MzNkNDgwZDg4MmZjNzkyNjI1NWIwYTUyMzAwOGVlZWU0ZWRiYmZjZmY2OTRjNDc5ZTlmMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bp6-j9f2YkBCKNuhPAu2_JoP7IfRq8mtkMKOFwkQtUY)
> 
> 可以看下是什么私信内容吗

![Screenshot_2024-03-15-08-26-50-438_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/54608551/f145951e-c685-4b6a-b92b-ca7f18f55770)
![Screenshot_2024-03-15-08-26-54-725_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/54608551/efff5c23-b843-4566-918e-d639054fa8fe)

**Comment by guozhigq** [comment]
你把错误日志清除了，然后再触发一次异常  看看错误日志呢

**Comment by PRO-2684** [comment]
> 你把错误日志清除了，然后再触发一次异常 看看错误日志呢

```
Pilipala错误日志 
 ********************
------- 设备信息 -------
id: TKQ1.220829.002
board: mars
bootloader: unknown
brand: Xiaomi
device: mars
display: TKQ1.220829.002 test-keys
fingerprint: Xiaomi/mars/mars:13/TKQ1.220829.002/V14.0.11.0.TKACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-338300-gbqdq-hqj3m-hnk6z
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102K1AC
product: mars
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.11.0.TKACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-09-01
------- 应用信息 -------
environment: release
version: 1.0.21
appName: PiliPala
buildNumber: 10213
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
type 'Null' is not a subtype of type 'String'
------- 错误堆栈 -------
#0      _WhisperPageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:pilipala/pages/whisper/view.dart:171)
#1      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1422)
#2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:490)
#3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:829)
#4      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:843)
#5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835)
#6      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:835)
#7      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349)
#8      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657)
#9      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071)
#10     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657)
#11     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338)
#12     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:486)
#13     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239)
#14     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:281)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#16     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
#17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601)
#20     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1925)
#21     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1876)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#23     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#26     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#29     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#32     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#35     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#38     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#41     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#46     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#49     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
#50     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808)
#51     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#53     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#54     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:494)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#56     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#59     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#62     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#65     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#68     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#71     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#74     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#77     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#79     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#81     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#82     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
#83     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:581)
#84     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:608)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#86     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#87     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
#88     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:868)
#89     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#91     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#92     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173)
#93     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062)
#94     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237)
#95     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403)
#96     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385)
#97     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025)
#98     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038)
#99     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591)
#100    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986)
#101    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#102    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#103    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#104    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#105    _invoke (dart:ui/hooks.dart:312)
#106    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#107    _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------
```
