### ISSUE TITLE
［Bug］请求错误 于 视频播放

### ISSUE THREAD

**Issue by 0xarch** [guozhigq/pilipala#496]
### 问题描述
请求错误，无法加载视频，非视频可加载

### 复现步骤
点击首页任意视频。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
RedmiK70E
HyperOS1.0.8
Android14

### Pilipala错误日志 
```
 ********************
------- 设备信息 -------
id: UP1A.230905.011
board: duchamp
bootloader: unknown
brand: Redmi
device: duchamp
display: UP1A.230905.011
fingerprint: Redmi/duchamp/duchamp:14/UP1A.230905.011/V816.0.8.0.UNLCNXM:user/release-keys
hardware: mt6897
host: pangu-build-component-system-231178-rtkv0-48b1r-9hs82
isPhysicalDevice: true
manufacturer: Xiaomi
model: 2311DRK48C
product: duchamp
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V816.0.8.0.UNLCNXM
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2023-12-01
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPala
buildNumber: 10193
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
RangeError (length): Invalid value: Valid value range is empty: -1
------- 错误堆栈 -------
#0      VideoPlayerServiceHandler.onVideoDetailDispose (package:pilipala/services/audio_handler.dart)
#1      _VideoDetailPageState.dispose (package:pilipala/pages/video/detail/view.dart:201)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5680)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2067)
#4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#5      _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#8      RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#11     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#14     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#17     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#20     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#23     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#26     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#29     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#32     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#35     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#38     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#41     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#44     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#47     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#50     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#53     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#56     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#59     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#62     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#65     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#68     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#71     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#74     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#77     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#80     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#83     _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#86     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#88     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#89     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#90     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#91     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#92     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#93     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#94     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#95     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#96     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#97     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#98     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#99     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#100    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#101    _RawViewElement.visitChildren (package:flutter/src/widgets/view.dart:382)
#102    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#103    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#104    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#105    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#106    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#107    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#108    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#109    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#110    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#111    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#112    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065)
#113    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1288)
#114    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063)
#115    ListIterable.forEach (dart:_internal/iterable.dart:49)
#116    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2076)
#117    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2755)
#118    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3165)
#119    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:987)
#120    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#121    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#122    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#123    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#124    _invoke (dart:ui/hooks.dart:312)
#125    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#126    _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------```

**Comment by guozhigq** [comment]
试一试最新的release，昨晚覆盖更新了一版

**Comment by 0xarch** [comment]
解决了，谢谢
