### ISSUE TITLE
f-droid 1.0.19 版本的“app 端首页推荐”无法加载视频详情

### ISSUE THREAD

**Issue by GalaxySnail** [guozhigq/pilipala#523]
### 问题描述/复现步骤

使用 f-droid 上构建的 1.0.19 (10193) arm64-v8a 版本时，设置中“首页推荐类型”选择“app端”，能够加载出推荐视频列表，包括标题、封面、up主，但点击进入任意一个视频后报错“请求错误”，无法加载出视频信息，包括标题、视频简介、相关推荐，且无法播放视频，但评论区仍能够正常加载显示。GitHub 上下载的二进制无此问题，切换到 f-droid 后才出现。

### 预期行为

app 端推荐能够正常工作。

顺便一提，是否可以让 f-droid 构建与 GitHub 不同的包名，以此方便对比两个构建的行为区别？另外最好是能导入导出设置，会更方便些（

### 相关截图或日志

<details>

<summary>展开截图</summary>

![](https://github.com/guozhigq/pilipala/assets/53637421/ee8b8377-39b0-4a52-b6af-880ae71a3383)

</details>

<details>

<summary>报错信息1：2024-02-07 23:00:57 <code>NoSuchMethodError: The method '[]' was called on null.</code></summary>

```
Pilipala错误日志 
 ********************
------- 设备信息 -------
id: QKQ1.190915.002
board: violet
bootloader: unknown
brand: xiaomi
device: violet
display: QKQ1.190915.002
fingerprint: xiaomi/violet/violet:10/QKQ1.190915.002/20.6.4:user/release-keys
hardware: qcom
host: c4-miui-ota-bd42.bj
isPhysicalDevice: true
manufacturer: Xiaomi
model: Redmi Note 7 Pro
product: violet
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPala
buildNumber: 10193
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("status")
------- 错误堆栈 -------
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      VideoIntroController.queryOnlineTotal (package:pilipala/pages/video/detail/introduction/controller.dart:505)
<asynchronous suspension>
------- CUSTOM INFO -------
```

</details>

<details>

<summary>报错信息2：2024-02-07 23:00:58 <code>type 'String' is not a subtype of type 'int' of 'index'</code></summary>

```
Pilipala错误日志 
 ********************
------- 设备信息 -------
id: QKQ1.190915.002
board: violet
bootloader: unknown
brand: xiaomi
device: violet
display: QKQ1.190915.002
fingerprint: xiaomi/violet/violet:10/QKQ1.190915.002/20.6.4:user/release-keys
hardware: qcom
host: c4-miui-ota-bd42.bj
isPhysicalDevice: true
manufacturer: Xiaomi
model: Redmi Note 7 Pro
product: violet
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPala
buildNumber: 10193
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
type 'String' is not a subtype of type 'int' of 'index'
------- 错误堆栈 -------
#0      VideoIntroController.queryHasCoinVideo (package:pilipala/pages/video/detail/introduction/controller.dart:151)
<asynchronous suspension>
------- CUSTOM INFO -------
```

</details>

**Comment by guozhigq** [comment]
1.0.19 后来更新过一版，本地打包直接上传到release的，所以没有触发 ci。
对比两个构建的行为，这个有什么作用，没明白
导出设置下次重装时方便直接导入？

**Comment by GalaxySnail** [comment]
> 1.0.19 后来更新过一版，本地打包直接上传到release的，所以没有触发 ci。

一般来说最好不要在同一个版本号上修改代码重新发布。我建议稍微改变一下版本号策略，改成 `1.0.19.0` 或者 `1.19.0`，如果再遇到这类需要重新发布的情况，可以把末尾版本号加一然后发个新版，在 changelog 里也可以提一句修复了什么东西。

不太清楚像 10193 这样的版本号需不需要改，如果可以不改动的话最好，这样可以覆盖安装；不过我依稀记得 f-droid 好像是需要提高这个版本号才会重新构建，但我也不了解这个，记忆也比较模糊，需要求证一下（

> 对比两个构建的行为，这个有什么作用，没明白

就是说万一相同的代码在 f-droid 上构建出了问题，共存两个版本可以方便对比两个构建的行为具体有什么区别，不需要卸载重装来比较。

> 导出设置下次重装时方便直接导入？

是的，也可以备份、或迁移到其它手机上。
