### ISSUE TITLE
通过合集切换视频，评论有概率不会切换

### ISSUE THREAD

**Issue by ShiraYukey** [guozhigq/pilipala#525]
### 问题描述
通过合集切换视频，评论有概率不会切换，还是之前视频的评论。

### 复现步骤
点开属于某个合集的视频的详情页，点击合集，切换其他视频。

### 预期行为
切换到对应视频的评论。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
```
Pilipala错误日志 
 ********************
------- 设备信息 -------
id: UQ1A.231205.015
board: msmnile
bootloader: unknown
brand: Xiaomi
device: raphael
display: UQ1A.231205.015
fingerprint: Xiaomi/lineage_raphael/raphael:14/UQ1A.231205.015/1704624061:user/release-keys
hardware: qcom
host: android-build
isPhysicalDevice: true
manufacturer: Xiaomi
model: Redmi K20 Pro
product: lineage_raphael
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 1704624061
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2023-12-05
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPala
buildNumber: 10193
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
Bad state: Cannot add event after closing
------- 错误堆栈 -------
#0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:56)
<asynchronous suspension>
------- CUSTOM INFO -------
```

**Comment by guozhigq** [comment]
v1.0.20 中已解决，可以观察一下。
