### ISSUE TITLE
硬解开视频卡死

### ISSUE THREAD

**Issue by nuclearchain** [guozhigq/pilipala#542]
### 问题描述
请提供一个清晰而简明的问题描述。
打开视频卡住，有时系统也会卡死
### 复现步骤
请提供复现该问题所需的具体步骤。
打开硬解，开视频
### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
小米11pro    miui14.0.13
### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
Pilipala错误日志 
 ********************
------- 设备信息 -------
id: TKQ1.220829.002
board: mars
bootloader: unknown
brand: Xiaomi
device: mars
display: TKQ1.220829.002 test-keys
fingerprint: Xiaomi/mars/mars:13/TKQ1.220829.002/V14.0.13.0.TKACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-505941-5rgj1-81ck5-wpd4q
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102K1AC
product: mars
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.13.0.TKACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-12-01
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPala
buildNumber: 10193
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
Bad state: No element
------- 错误堆栈 -------
#0      Stream.first.<anonymous closure> (dart:async/stream.dart:1583)
#1      _RootZone.runGuarded (dart:async/zone.dart:1582)
#2      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392)
#3      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402)
#4      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291)
#5      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99)
#6      _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161)
#7      _RootZone.runGuarded (dart:async/zone.dart:1582)
#8      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392)
#9      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402)
#10     _DelayedDone.perform (dart:async/stream_impl.dart:534)
#11     _PendingEvents.handleNext (dart:async/stream_impl.dart:620)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
------- CUSTOM INFO -------
https://github.com/guozhigq/pilipala/assets/90886320/52e84d12-cd61-40f1-b780-e914423c6f6a

**Comment by nuclearchain** [comment]
Pilipala错误日志 
 ********************
------- 设备信息 -------
id: TKQ1.220829.002
board: mars
bootloader: unknown
brand: Xiaomi
device: mars
display: TKQ1.220829.002 test-keys
fingerprint: Xiaomi/mars/mars:13/TKQ1.220829.002/V14.0.13.0.TKACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-505941-5rgj1-81ck5-wpd4q
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102K1AC
product: mars
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.13.0.TKACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-12-01
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPala
buildNumber: 10193
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
HttpException: Invalid statusCode: 503, uri = https://files.catbox.moe/8uc48f.png@100q.webp
------- 错误堆栈 -------
------- CUSTOM INFO -------

**Comment by rurudo-ruo** [comment]
同样的问题 小米11Ultra MIUI14.0.13 安卓13
硬解任意编码的视频都有卡死现象，hevc最为严重，轻则卡死app重则卡死系统；avc编码比较好，卡着一会儿自己好了
错误日志
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-11-08 23:36:40.352421

------- DEVICE INFO -------
id: TKQ1.220829.002
board: star
bootloader: unknown
brand: Xiaomi
device: star
display: TKQ1.220829.002 test-keys
fingerprint: Xiaomi/star/star:13/TKQ1.220829.002/V14.0.13.0.TKACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-505941-5rgj1-81ck5-wpd4q
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102K1C
product: star
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.13.0.TKACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-12-01

------- APP INFO -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala

---------- ERROR ----------
type 'Null' is not a subtype of type 'List<dynamic>'

------- STACK TRACE -------
#0      VideoHttp.getSubtitleContent (package:pilipala/http/video.dart:540)
<asynchronous suspension>
#1      VideoDetailController.getDanmaku (package:pilipala/pages/video/detail/controller.dart:469)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-11-08 23:36:44.529716

------- DEVICE INFO -------
id: TKQ1.220829.002
board: star
bootloader: unknown
brand: Xiaomi
device: star
display: TKQ1.220829.002 test-keys
fingerprint: Xiaomi/star/star:13/TKQ1.220829.002/V14.0.13.0.TKACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-505941-5rgj1-81ck5-wpd4q
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102K1C
product: star
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.13.0.TKACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-12-01

------- APP INFO -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala

---------- ERROR ----------
Bad state: Cannot add event after closing

------- STACK TRACE -------
#0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:67)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-11-08 23:36:46.063322

------- DEVICE INFO -------
id: TKQ1.220829.002
board: star
bootloader: unknown
brand: Xiaomi
device: star
display: TKQ1.220829.002 test-keys
fingerprint: Xiaomi/star/star:13/TKQ1.220829.002/V14.0.13.0.TKACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-505941-5rgj1-81ck5-wpd4q
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102K1C
product: star
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.13.0.TKACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-12-01

------- APP INFO -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala

---------- ERROR ----------
type 'Null' is not a subtype of type 'List<dynamic>'

------- STACK TRACE -------
#0      VideoHttp.getSubtitleContent (package:pilipala/http/video.dart:540)
<asynchronous suspension>
#1      VideoDetailController.getDanmaku (package:pilipala/pages/video/detail/controller.dart:469)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-11-08 23:50:42.818341

------- DEVICE INFO -------
id: TKQ1.220829.002
board: star
bootloader: unknown
brand: Xiaomi
device: star
display: TKQ1.220829.002 test-keys
fingerprint: Xiaomi/star/star:13/TKQ1.220829.002/V14.0.13.0.TKACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-505941-5rgj1-81ck5-wpd4q
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102K1C
product: star
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.13.0.TKACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-12-01

------- APP INFO -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala

---------- ERROR ----------
type 'Null' is not a subtype of type 'List<dynamic>'

------- STACK TRACE -------
#0      VideoHttp.getSubtitleContent (package:pilipala/http/video.dart:540)
<asynchronous suspension>
#1      VideoDetailController.getDanmaku (package:pilipala/pages/video/detail/controller.dart:469)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-11-08 23:52:24.244304

------- DEVICE INFO -------
id: TKQ1.220829.002
board: star
bootloader: unknown
brand: Xiaomi
device: star
display: TKQ1.220829.002 test-keys
fingerprint: Xiaomi/star/star:13/TKQ1.220829.002/V14.0.13.0.TKACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-505941-5rgj1-81ck5-wpd4q
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102K1C
product: star
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.13.0.TKACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-12-01

------- APP INFO -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala

---------- ERROR ----------
Bad state: Cannot add event after closing

------- STACK TRACE -------
#0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:67)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-11-08 23:52:49.223810

------- DEVICE INFO -------
id: TKQ1.220829.002
board: star
bootloader: unknown
brand: Xiaomi
device: star
display: TKQ1.220829.002 test-keys
fingerprint: Xiaomi/star/star:13/TKQ1.220829.002/V14.0.13.0.TKACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-505941-5rgj1-81ck5-wpd4q
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102K1C
product: star
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.13.0.TKACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-12-01

------- APP INFO -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala

---------- ERROR ----------
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("heroTag")

------- STACK TRACE -------
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      _HeaderControlState.initState (package:pilipala/pages/video/detail/widgets/header_control.dart:70)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5611)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
#27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#38     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893)
#39     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6905)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#43     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#46     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
#47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#49     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893)
#50     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6905)
#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#54     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#57     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
#58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#62     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#65     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
#66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3840)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#70     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#72     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
#73     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
#74     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
#75     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
#76     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
#77     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
#78     _invoke (dart:ui/hooks.dart:312)
#79     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
#80     _drawFrame (dart:ui/hooks.dart:283)

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-11-08 23:54:56.005636

------- DEVICE INFO -------
id: TKQ1.220829.002
board: star
bootloader: unknown
brand: Xiaomi
device: star
display: TKQ1.220829.002 test-keys
fingerprint: Xiaomi/star/star:13/TKQ1.220829.002/V14.0.13.0.TKACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-505941-5rgj1-81ck5-wpd4q
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102K1C
product: star
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.13.0.TKACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-12-01

------- APP INFO -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala

---------- ERROR ----------
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("heroTag")

------- STACK TRACE -------
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      _HeaderControlState.initState (package:pilipala/pages/video/detail/widgets/header_control.dart:70)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5611)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
#27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#38     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893)
#39     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6905)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#43     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#46     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
#47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#49     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893)
#50     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6905)
#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#54     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#57     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
#58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#59     Element.inflateWidget (pa
