### ISSUE TITLE
[Bug] 长按两个视频卡片同时弹出两张封面，第二张关不掉。

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#596]
### 问题描述
在首页推荐或视频相关推荐同时长按两个视频卡片，同时弹出的两张封面只能关掉第一张。必须杀死APP重启。

### 复现步骤
见下

### 预期行为
第二张封面可以关闭，或者阻断第二次长按的响应。

### 系统信息
Device: OPPO A33
OS: Android 5.1
Webview: v95

### 相关截图或日志

https://github.com/guozhigq/pilipala/assets/89803422/ae254bc9-4578-43a3-a2b9-b7fb96aa63fd

```
Pilipala错误日志 
 ********************
------- 设备信息 -------
id: LMY47V
board: msm8916
bootloader: unknown
brand: OPPO
device: A33
display: A33_11_A.11_160729
fingerprint: OPPO/A33/A33:5.1.1/LMY47V/1390465867:user/release-keys
hardware: qcom
host: ubuntu-121-102
isPhysicalDevice: true
manufacturer: OPPO
model: OPPO A33
product: A33
tags: dev-keys
type: user
versionBaseOs: null
versionCodename: REL
versionIncremental: eng.root.20160729.193949
versionPreviewSdk: null
versionRelease: 5.1.1
versionSdk: 22
versionSecurityPatch: null
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPala
buildNumber: 10193
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
Null check operator used on a null value
------- 错误堆栈 -------
#0      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:170)
#1      OverlayPop.build.<anonymous closure> (package:pilipala/common/widgets/overlay_pop.dart:47)
#2      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#6      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)
#7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492)
#9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439)
#11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#12     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#15     _invoke1 (dart:ui/hooks.dart:328)
#16     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
------- CUSTOM INFO -------
```

**Comment by guozhigq** [comment]
最新版本已修复

**Comment by VillagerTom** [comment]
@orz12 merge一下（不是

**Comment by orz12** [comment]
> @orz12 merge一下（不是

？
