### ISSUE TITLE
偶发的视频详情页灰屏

### ISSUE THREAD

**Issue by duyraven** [guozhigq/pilipala#730]
### 问题描述
主界面点进去视频详情灰屏

### 复现步骤
复现不出来，使用一段时间遇到的

### 相关截图或日志

https://github.com/guozhigq/pilipala/assets/54952917/ac598615-080f-485e-acdd-e490c37cbee6

Pilipala错误日志 
 ********************
------- 设备信息 -------
id: TKQ1.221114.001
board: thyme
bootloader: unknown
brand: Xiaomi
device: thyme
display: TKQ1.221114.001 test-keys
fingerprint: Xiaomi/thyme/thyme:13/TKQ1.221114.001/V14.0.20.0.TMACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-385380-m6tb5-r4th8-4zplw
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102J2SC
product: thyme
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.20.0.TMACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-10-01
------- 应用信息 -------
environment: release
version: 1.0.23
appName: PiliPala
buildNumber: 10233
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
Bad state: Cannot add event after closing
------- 错误堆栈 -------
#0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:67)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by guozhigq** [comment]
确实不好复现

**Comment by Maolaohei** [comment]
感觉和小米设备有关系，我用的红米K60经常遇到这个问题，但是看错误日志是空的
